version: '2'
services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-app:/var/www/laravel-app
  phpfpm:
    build: ./fpm
    container_name: "laravel-phpfpm"
    volumes:
      - ./laravel-app:/var/www/laravel-app
